# Generated by Django 5.1.15 on 2026-06-24 14:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=50)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='PlatformWaitlist',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('contact', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('icon', models.CharField(default='🚗', max_length=50)),
                ('wash_goal', models.IntegerField(default=8)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Washstation',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('plan', models.CharField(default='free', max_length=50)),
                ('plan_expires_at', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('free_limit', models.IntegerField(default=50)),
                ('washstation_logo', models.CharField(blank=True, max_length=500, null=True)),
                ('theme_color', models.CharField(default='#0ea5e9', max_length=7)),
                ('qr_code', models.CharField(blank=True, max_length=500, null=True)),
                ('wifi_name', models.CharField(blank=True, max_length=255, null=True)),
                ('wifi_password', models.CharField(blank=True, max_length=255, null=True)),
                ('wifi_type', models.CharField(blank=True, max_length=50, null=True)),
                ('wifi_hidden', models.BooleanField(default=False)),
                ('sms_enabled', models.BooleanField(default=False)),
                ('sms_api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('sms_sender_id', models.CharField(default='CleanPass', max_length=50)),
                ('esewa_id', models.CharField(blank=True, max_length=100, null=True)),
                ('khalti_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('plate_no', models.CharField(max_length=50)),
                ('make', models.CharField(blank=True, max_length=100, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='washstation.customer')),
                ('vehicle_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='washstation.vehicletype')),
                ('washstation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='washstation.washstation')),
            ],
            options={
                'unique_together': {('plate_no', 'washstation')},
            },
        ),
        migrations.CreateModel(
            name='WashPackage',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.IntegerField()),
                ('stamp_value', models.IntegerField(default=1)),
                ('color', models.CharField(default='#0ea5e9', max_length=7)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('vehicle_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packages', to='washstation.vehicletype')),
                ('washstation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='washstation.washstation')),
            ],
        ),
        migrations.CreateModel(
            name='WashRequest',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=50)),
                ('plate_no', models.CharField(max_length=50)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wash_requests', to='washstation.customer')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wash_requests', to='washstation.washpackage')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wash_requests', to='washstation.vehicle')),
                ('vehicle_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wash_requests', to='washstation.vehicletype')),
                ('washstation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wash_requests', to='washstation.washstation')),
            ],
        ),
        migrations.CreateModel(
            name='WaitlistItem',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('contact', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('washstation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_items', to='washstation.washstation')),
            ],
        ),
        migrations.AddField(
            model_name='vehicletype',
            name='washstation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_types', to='washstation.washstation'),
        ),
        migrations.AddField(
            model_name='customer',
            name='washstation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='washstation.washstation'),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=50)),
                ('time_slot', models.CharField(max_length=50)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='washstation.vehicle')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='washstation.washpackage')),
                ('washstation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='washstation.washstation')),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('pin', models.CharField(default='0000', max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('commission', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('washstation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='washstation.washstation')),
            ],
        ),
        migrations.CreateModel(
            name='Wash',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('paid', models.BooleanField(default=True)),
                ('payment_method', models.CharField(blank=True, default='cash', max_length=50, null=True)),
                ('redeemed', models.BooleanField(default=False)),
                ('redeemed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='done', max_length=50)),
                ('wash_start_at', models.DateTimeField(blank=True, null=True)),
                ('wash_done_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='washes', to='washstation.vehicle')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='washes', to='washstation.washpackage')),
                ('washstation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='washes', to='washstation.washstation')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='washes', to='washstation.worker')),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('clock_in', models.DateTimeField(default=django.utils.timezone.now)),
                ('clock_out', models.DateTimeField(blank=True, null=True)),
                ('washstation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='washstation.washstation')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='washstation.worker')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('phone', 'washstation')},
        ),
    ]
