# Generated by Django 5.1.15 on 2026-06-28 09:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=50)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlatformWaitlist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contact', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('icon', models.CharField(default='🚗', max_length=50)),
                ('wash_goal', models.IntegerField(default=8)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plate_no', models.CharField(max_length=50)),
                ('make', models.CharField(blank=True, max_length=100, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='washstation.customer')),
                ('vehicle_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='washstation.vehicletype')),
            ],
        ),
        migrations.CreateModel(
            name='WashPackage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.IntegerField()),
                ('stamp_value', models.IntegerField(default=1)),
                ('color', models.CharField(default='#0ea5e9', max_length=7)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packages', to='washstation.vehicletype')),
            ],
        ),
        migrations.CreateModel(
            name='Washstation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('plan', models.CharField(choices=[('free', 'Free'), ('basic', 'Basic'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], default='free', max_length=50)),
                ('plan_expires_at', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('free_limit', models.IntegerField(default=50)),
                ('washstation_logo', models.CharField(blank=True, max_length=500, null=True)),
                ('theme_color', models.CharField(default='#0ea5e9', max_length=7)),
                ('qr_code', models.CharField(blank=True, max_length=500, null=True)),
                ('wifi_name', models.CharField(blank=True, max_length=255, null=True)),
                ('wifi_password', models.CharField(blank=True, max_length=255, null=True)),
                ('wifi_type', models.CharField(blank=True, max_length=50, null=True)),
                ('wifi_hidden', models.BooleanField(default=False)),
                ('sms_enabled', models.BooleanField(default=False)),
                ('sms_api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('sms_sender_id', models.CharField(default='CleanPass', max_length=50)),
                ('esewa_id', models.CharField(blank=True, max_length=100, null=True)),
                ('khalti_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='washstation', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WashRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=50)),
                ('plate_no', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wash_requests', to='washstation.customer')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wash_requests', to='washstation.washpackage')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wash_requests', to='washstation.vehicle')),
                ('vehicle_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wash_requests', to='washstation.vehicletype')),
                ('washstation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wash_requests', to='washstation.washstation')),
            ],
        ),
        migrations.AddField(
            model_name='washpackage',
            name='washstation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='washstation.washstation'),
        ),
        migrations.CreateModel(
            name='WaitlistItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contact', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('washstation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_items', to='washstation.washstation')),
            ],
        ),
        migrations.AddField(
            model_name='vehicletype',
            name='washstation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_types', to='washstation.washstation'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='washstation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='washstation.washstation'),
        ),
        migrations.AddField(
            model_name='customer',
            name='washstation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='washstation.washstation'),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time_slot', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='washstation.vehicle')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='washstation.washpackage')),
                ('washstation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='washstation.washstation')),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('pin', models.CharField(default='0000', max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('commission', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('washstation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='washstation.washstation')),
            ],
        ),
        migrations.CreateModel(
            name='Wash',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('paid', models.BooleanField(default=True)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('esewa', 'eSewa'), ('khalti', 'Khalti'), ('credit', 'Credit'), ('free', 'Free')], default='cash', max_length=20)),
                ('redeemed', models.BooleanField(default=False)),
                ('redeemed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('washing', 'Washing'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='queued', max_length=20)),
                ('wash_start_at', models.DateTimeField(blank=True, null=True)),
                ('wash_done_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='washes', to='washstation.vehicle')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='washes', to='washstation.washpackage')),
                ('washstation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='washes', to='washstation.washstation')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='washes', to='washstation.worker')),
            ],
            options={
                'verbose_name_plural': 'Washes',
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('clock_in', models.DateTimeField(auto_now_add=True)),
                ('clock_out', models.DateTimeField(blank=True, null=True)),
                ('washstation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='washstation.washstation')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='washstation.worker')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='vehicle',
            unique_together={('plate_no', 'washstation')},
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('phone', 'washstation')},
        ),
    ]
