# Generated by Django 5.1.15 on 2026-07-01 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('washstation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wash',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('washing', 'Washing'), ('ready', 'Ready'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='queued', max_length=20),
        ),
        migrations.AlterField(
            model_name='washstation',
            name='washstation_logo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
