# Generated by Django 5.1.15 on 2026-07-01 07:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('washstation', '0002_alter_wash_status_alter_washstation_washstation_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='WashService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('washstation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='washstation.washstation')),
            ],
        ),
        migrations.AddField(
            model_name='wash',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='washes', to='washstation.washservice'),
        ),
        migrations.AddField(
            model_name='washrequest',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='wash_requests', to='washstation.washservice'),
        ),
    ]
